accelerator: gpu
accumulate_grad_batches: 1
annotation: /gpfs/home/22054/jinyu/zyx/cheXpert_plus/CoT_cheXpert_plus.json
base_dir: /gpfs/home/22054/jinyu/zyx/cheXpert_plus/PNG/
batch_size: 6
beam_size: 3
ckpt_file: null
cot: true
dataset: mimic_cxr
delta_file: null
devices: 1
diversity_penalty: 0
do_sample: false
end_sym: </s>
epoch_save_ckpt: 3
every_n_train_steps: 0
freeze_vm: false
global_only: false
gradient_clip_val: null
input_size: 224
learning_rate: 0.0001
length_penalty: 2.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
llama_model: null
llm_alpha: 16
llm_r: 16
llm_use_lora: false
lora_dropout: 0.1
low_resource: false
max_epochs: 11
max_length: 100
max_new_tokens: 120
min_new_tokens: 80
no_repeat_ngram_size: 2
num_beam_groups: 1
num_nodes: 1
num_sanity_val_steps: 1
num_workers: 6
optimizer: adam
precision: bf16-mixed
prefetch_factor: 4
projection_dim: 2048
repetition_penalty: 2.0
savedmodel_path: save/mimic_cxr/chexpert
scorer_types:
- Bleu_4
- CIDEr
strategy: deepspeed
temperature: 0
test: false
test_batch_size: 16
text_encoder_type: Bio_ClinicalBERT
type: large
val_batch_size: 6
val_check_interval: 0.5
validate: false
vis_alpha: 16
vis_r: 16
vis_use_lora: false
vision_model: configs/MambaXrayCLIP-L.pth
weight_decay: 0.001
weights:
- 0.8
- 0.2
